### ISSUE TITLE
2.8.0 production energy meter values?

### ISSUE THREAD

**Issue by EckhardM** [SonnenladenGmbH/tibber_local_lib#1]
Hi, does it also provide the production meter values (2.8.0)?

**Comment by SonnenladenGmbH** [comment]
Hi @EckhardM 

this is the only data we can retrieve from the pulse / energy meter at the moment. 
*We'll add more in the future*
```
Device ID: 0901454d41200099e91f
Current Power (W): 1530.2
Total Consumption (Wh): 19311451.7
Tariff 1 Consumption (Wh): 19311451.7
Tariff 2 Consumption (Wh): 0.0
```

I can't confirm 100% but the 2.8.0 values should be 'Tariff 2' in this case. 
'Current Power' will go negative if you feed energy to the grid.

**Comment by EckhardM** [comment]
I took a look into your tibber_local_lib/decoder.py, you only check the values for the following OBIS:

- 0100100700ff  # OBIS code for current power (W) (16.7.0)
- 0100010800ff # OBIS code for total consumption (Wh) (1.8.0)
- 0100010801ff # OBIS code for tariff 1 consumption (Wh) (1.8.1)
- 0100010802ff  # OBIS code for tariff 2 consumption (Wh) (1.8.2)
- 0100000009ff  # OBIS code for current power (W) - that comment is wrong, that is the meter ID!

The production value of a two direction meter is 2.8.0 - or obis 0100020800ff. This is not yet provided by you.

You will get the full SML record from the meter via Tibber Pulse. So you will be able to provide the production data if the meter returns it.

**Comment by SonnenladenGmbH** [comment]
Oh you're right! 
I'll definitely implement that later today!

**Comment by EckhardM** [comment]
Another hint: SML provides the units and decimals multipliers also in the SML stream. `smllib` uses that in the value `scaler` from the `get_obis` function. You coded the division by 10 fix. Based on the actual numbers that could be wrong.

**Comment by SonnenladenGmbH** [comment]
I just rechecked. This is all data I can retrieve from my meter which is not a lot...

[<obis: 0100000009ff, value: 0901454d4800009XXXX>, <obis: 0100010800ff, status: 386, unit: 30, scaler: -1, value: 195709519>, <obis: 0100010801ff, unit: 30, scaler: -1, value: 195709519>, <obis: 0100010802ff, unit: 30, scaler: -1, value: 0>, <obis: 0100100700ff, unit: 27, scaler: -1, value: 5095>]

**Comment by EckhardM** [comment]
It seems that your meter is a one direction meter that does not provide production data with obis 2.8.0. Let me see if I can test this  with my meter and create a pull request. I already used `smllib` before when I catched the SML data directly from the meter (without Tibber Pulse formerly).  The instructions how to enable the web server in the bridge permanently were the most valuable piece here. I will come back when I got data from the bridge directly.

**Comment by SonnenladenGmbH** [comment]
Yes, that can be the reason. However, shouldn’t there be more values, such as each phase voltage and current, present nonetheless?

Feel free to do a pull with the changes and optimizations! 🙏

**Comment by EckhardM** [comment]
This is a real SML record from my meter. You can convert it with `bytes.fromhex()` and add it to the stream for testing.

`1b1b1b1b0101010176050a26a1fb6200620072630101760107ffffffffffff05036235ff0b0a01454d4800009f38467262016503623bd462016391bb0076050a26a1fc62006200726307017707ffffffffffff0b0a01454d4800009f3846070100620affff7262016503623bd47577070100603201010101010104454d480177070100600100ff010101010b0a01454d4800009f38460177070100010800ff641c11047262016503623bd4621e52ff65025fc8ef0177070100020800ff017262016503623bd4621e52ff6502deb2810177070100100700ff0101621b520052320101016339160076050a26a1fd620062007263020171016378d900001b1b1b1b1a013003`

That is the output from `smllib`:

`[<obis: 010060320101, value: EMH>,
 <obis: 0100600100ff, value: 0a01454d4800009f3846>,
 <obis: 0100010800ff, status: 1839364, val_time: 56769492, unit: 30, scaler: -1, value: 39831791>,
 <obis: 0100020800ff, val_time: 56769492, unit: 30, scaler: -1, value: 48149121>,
 <obis: 0100100700ff, unit: 27, scaler: 0, value: 50>]
`

**Comment by EckhardM** [comment]
> Yes, that can be the reason. However, shouldn’t there be more values, such as each phase voltage and current, present nonetheless?

No, my meter provides no voltages and currents too. See above!

**Comment by SonnenladenGmbH** [comment]
I see... You also got some other different obis codes for your meter... 

So I think I'll remove the option to call for `Tariff 1 Consumption` and `Tariff 2 Consumption` and just replace those both with `Consumption 1.8.0`...

Will also add `Feed in 2.8.0` or similar for the fed in power to the grid...

Retrieving the meter ID also seems to be different with your meter.. So maybe I'll just remove that as well...

This is probably the most universal approach to support most meters...

I'll add a function to print all available obis data / SML record data to extract values that may be needed additionally for some users...

**Comment by SonnenladenGmbH** [comment]
I just released v.1.2.0 with all the changes we discussed. View the release notes here: https://github.com/SonnenladenGmbH/tibber_local_lib/releases/tag/1.2.0

Thanks for your contribution!
Feel free to contact me to get a great discount on your next purchase of photovoltaic components in our online shop:
https://www.sonnenladen.de/

Have a great week 🌳☀️✌️
