### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by EckhardM** [SonnenladenGmbH/tibber_local_lib#2]
Hi, ich schreibe hier mal in Deutsch: 

Ich bin der Anleitung gefolgt, um den lokalen Zugang einzuschalten. Folgende Punkte sind anders als beschrieben: 

- Wenn die Bridge im Access-Point-Modus ist, ist sie nicht per Name (tibber-host.fritz.box o.a.) erreichbar. Ich musste in meinem Computer herausfinden, was die Adresse des Default-Routers ist, den das WLAN zugewiesen hat. Bei mir war es 10.133.70.1, unter der ich die Bridge erreichen und die Änderungen an der Konfig durchführen konnte. (Scheinbar ist das die Standardadresse als AP.)

- Es ist zu beachten, welche NodeId der Pulse im Reiter NODES hat. Bei mir ist das nicht die 1, sondern die 5. Daher ist die URL zum Abrufen der SML-Daten bei mir `http://tibber-host/data.json?node_id=5`

- Das Wiederverbinden mit meinem WLAN dauerte einige Minuten, hier ist Geduld gefragt, bis der Ring wieder blau war.

**Comment by SonnenladenGmbH** [comment]
Hi,
sorry for the delay. I just had time to fix these issues.

One can manually define the correct nodeId by doing initialization like this now:

  **Example of initialization:**
  `tibber_pulse = SMLDecoder(tibber_pulse_host, auth)` <--- undefined will use nodeId 1 by default
  `tibber_pulse = SMLDecoder(tibber_pulse_host, auth, nodeId=2)` <--- will use nodeId 2 for example

----------

As already written in the doc you obviously have to find out your correct IP or hostname to connect and configure to your bridge. There is no standardised IP...  

---------

Depending on wifi strength it may take some time for the bridge to reconnect, you're right. On my side it was online fairly quickly again.

---------

Thanks for your feedback!
